### PR TITLE
Pictoralist Re-write

### PR DESCRIPTION
**Pull request by mackgalante**
Pull request tracking work on the re-write of Pictoralist.

This pull request intends to resolve the following issues:

- [x] #46
- [x] #47
- [x] #49
- [x] #63 
- [x] #107
- [x] #110

### CODE REVIEW

**Comment by zachll** [comment]
https://docs.google.com/presentation/d/1MhhTnN9NZB0JeoBXAJbIrOt-vx0S5sZuMqpVBV0p4CU/edit#slide=id.g15a6f946f42_0_654

**Comment by mackgalante** [comment]
Because Issue #112 is a pre-requisite for testing this script, going to go ahead with a workaround on pulling the comparator that the message is about. 

We know that the last item in the "is_about" key seems to consistently be the comparator, so we can rely on that for now for testing. I still think better architecture is a good thing, or at the very least documentation for anyone playing with cedar that going forward the message templates are sensitive to the ordering of the is_about fields.

**Comment by mackgalante** [comment]
Marked issue https://github.com/Display-Lab/precision-feedback-pipeline/issues/107 as resolved, can re-open on review if we think we need infrastructure for consecutive gaps at current date!

**Comment by mackgalante** [comment]
The graphs are done enough for further testing and commit to main, there are still some formatting hiccups that we need to work through. Going to take a look at LDT if I have some moxie this weekend to rework the automated output verification, then do bulk testing of the output messages with the new key formats.

All in all, coming along great

**Comment by mackgalante** [comment]
Manually resolved conflicts, should be fine to auto-merge now after review

**Comment by mackgalante** [comment]
Closed outstanding issues resolved by merging this branch, added issue for logging test progress on volume testing this branch.

As stated above, confident in merging tonight, have successful feedback generation from all personas once again. Volume testing will still make everyone sleep more soundly as pilot launch approaches

**Pull request merged**
