### PR TITLE
Remove denominators less than ten

### LINKED ISSUE #162: ALL ACCEPTABLE BYS are 'social- worse'
Mark did a stress test for more than 12000 records and Display LAB team did the test against leakdown tester with mark's sample input for 60 records and all input messages are returning 'Social worse' causal-pathway. Get one test case where the output must return another causal pathway but returns a social worse instead.

### LINKED ISSUE #175: Hotfix: Prevent feedback about old data
Need immediate solution to prevent data about a month that is not the most recent from being used to generate feedback messages.

- [ ] Piggyback off student_t_cleaner infrastructure
- [ ] Exclude measures without the most recent month found in the performance dataframe overall
- [ ] Verify fix via LDT

### PR DESCRIPTION
**Pull request by mackgalante**
Denominator based data cleaning is operational. Does not correct the problem identified in #162, however does accomplish what we set out to do, which is to remove measures from consideration if the data is not going to be large enough to be considered significant.

resolves #175

### CODE REVIEW

**Comment by mackgalante** [comment]
See issue 162 for further details on current progress

**Comment by zachll** [comment]
got these error messages:

    await self.middleware_stack(scope, receive, send)
  File "/Users/zachll/Library/Caches/pypoetry/virtualenvs/pfp-api-qTO9w-Mr-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/zachll/Library/Caches/pypoetry/virtualenvs/pfp-api-qTO9w-Mr-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/zachll/Library/Caches/pypoetry/virtualenvs/pfp-api-qTO9w-Mr-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/zachll/Library/Caches/pypoetry/virtualenvs/pfp-api-qTO9w-Mr-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/zachll/Library/Caches/pypoetry/virtualenvs/pfp-api-qTO9w-Mr-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/zachll/Library/Caches/pypoetry/virtualenvs/pfp-api-qTO9w-Mr-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/zachll/Library/Caches/pypoetry/virtualenvs/pfp-api-qTO9w-Mr-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/Users/zachll/Library/Caches/pypoetry/virtualenvs/pfp-api-qTO9w-Mr-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/zachll/Library/Caches/pypoetry/virtualenvs/pfp-api-qTO9w-Mr-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/zachll/Library/Caches/pypoetry/virtualenvs/pfp-api-qTO9w-Mr-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/Users/zachll/Library/Caches/pypoetry/virtualenvs/pfp-api-qTO9w-Mr-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/zachll/projects/precision-feedback-pipeline/./main.py", line 159, in createprecisionfeedback
    bs=Bit_stomach(performer_graph,performance_data_df)
  File "/Users/zachll/projects/precision-feedback-pipeline/./bit_stomach/bit_stomach.py", line 31, in __init__
    raise e
  File "/Users/zachll/projects/precision-feedback-pipeline/./bit_stomach/bit_stomach.py", line 29, in __init__
    self.performance_data_df=student_t_cleaner(performance_data)
  File "/Users/zachll/projects/precision-feedback-pipeline/./bit_stomach/student_t_cleaner.py", line 32, in student_t_cleaner
    raise ValueError("PROCESS_ABORTED")
ValueError: PROCESS_ABORTED

**Comment by zachll** [comment]
was using this input:

{
    "@context": {
      "@vocab": "http://schema.org/",
      "slowmo": "http://example.com/slowmo#",
      "csvw": "http://www.w3.org/ns/csvw#",
      "dc": "http://purl.org/dc/terms/",
      "psdo": "http://purl.obolibrary.org/obo/",
      "slowmo:Measure": "http://example.com/slowmo#Measure",
      "slowmo:IsAboutPerformer": "http://example.com/slowmo#IsAboutPerformer",
      "slowmo:ColumnUse": "http://example.com/slowmo#ColumnUse",
      "slowmo:IsAboutTemplate": "http://example.com/slowmo#IsAboutTemplate",
      "slowmo:spek": "http://example.com/slowmo#spek",
      "slowmo:IsAboutCausalPathway": "http://example.com/slowmo#IsAboutCausalPathway",
      "slowmo:IsAboutOrganization": "http://example.com/slowmo#IsAboutOrganization",
      "slowmo:IsAboutMeasure": "http://example.com/slowmo#IsAboutMeasure",
      "slowmo:InputTable": "http://example.com/slowmo#InputTable",
      "slowmo:WithComparator": "http://example.com/slowmo#WithComparator",
      "has_part": "http://purl.obolibrary.org/obo/bfo#BFO_0000051",
      "has_disposition": "http://purl.obolibrary.org/obo/RO_0000091"
    },
  "Performance_data":[
      ["staff_number","measure","month","passed_count","flagged_count","denominator","peer_average_comparator","peer_75th_percentile_benchmark","peer_90th_percentile_benchmark", "MPOG_goal"],
      [6,"NMB03","2023-01-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-02-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-03-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-04-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-05-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-06-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-07-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-08-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-09-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-10-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-11-01",100,0,100,90,92,96,90],
      [6,"NMB03","2023-12-01",80,20,100,90,92,96,90]
    ],
  "History":{
  },
  "Preferences":{
      "Utilities": {
      "Message_Format": 
        {
          "1": "0.0",
          "2": "0.1",
          "16": "7.5",
          "24": "9.4",
          "18": "11.3",
          "11": "13.2",
          "22": "15.1" ,
          "14": "22.6" ,
          "21": "62.3" ,
          "5":"0.2",
          "15":"4.0",
          "4":"0.9"
        },
      "Display_Format":
        {
          "short_sentence_with_no_chart": "0.0",
          "bar": "37.0",
          "line": "0.0"
        }
    }
  }
}

**Comment by mackgalante** [comment]
Already working on squashing that particular bug, it doesn't process the error handling correctly. Will be adding in code for both #175 resolution and this bug fix and re-testing.

**Comment by zachll** [comment]
Found another issue with the input below, when the current month was December with <10 cases, it reached back to November where there were >10 cases.

{
    "@context": {
      "@vocab": "http://schema.org/",
      "slowmo": "http://example.com/slowmo#",
      "csvw": "http://www.w3.org/ns/csvw#",
      "dc": "http://purl.org/dc/terms/",
      "psdo": "http://purl.obolibrary.org/obo/",
      "slowmo:Measure": "http://example.com/slowmo#Measure",
      "slowmo:IsAboutPerformer": "http://example.com/slowmo#IsAboutPerformer",
      "slowmo:ColumnUse": "http://example.com/slowmo#ColumnUse",
      "slowmo:IsAboutTemplate": "http://example.com/slowmo#IsAboutTemplate",
      "slowmo:spek": "http://example.com/slowmo#spek",
      "slowmo:IsAboutCausalPathway": "http://example.com/slowmo#IsAboutCausalPathway",
      "slowmo:IsAboutOrganization": "http://example.com/slowmo#IsAboutOrganization",
      "slowmo:IsAboutMeasure": "http://example.com/slowmo#IsAboutMeasure",
      "slowmo:InputTable": "http://example.com/slowmo#InputTable",
      "slowmo:WithComparator": "http://example.com/slowmo#WithComparator",
      "has_part": "http://purl.obolibrary.org/obo/bfo#BFO_0000051",
      "has_disposition": "http://purl.obolibrary.org/obo/RO_0000091"
    },
  "Performance_data":[
      ["staff_number","measure","month","passed_count","flagged_count","denominator","peer_average_comparator","peer_75th_percentile_benchmark","peer_90th_percentile_benchmark", "MPOG_goal"],
      [6,"NMB03","2023-01-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-02-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-03-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-04-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-05-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-06-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-07-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-08-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-09-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-10-01",90,10,100,90,92,96,90],
      [6,"NMB03","2023-11-01",100,0,100,90,92,96,90],
      [6,"NMB03","2023-12-01",1,1,2,90,92,96,90]
    ],
  "History":{
  },
  "Preferences":{
      "Utilities": {
      "Message_Format": 
        {
          "1": "0.0",
          "2": "0.1",
          "16": "7.5",
          "24": "9.4",
          "18": "11.3",
          "11": "13.2",
          "22": "15.1" ,
          "14": "22.6" ,
          "21": "62.3" ,
          "5":"0.2",
          "15":"4.0",
          "4":"0.9"
        },
      "Display_Format":
        {
          "short_sentence_with_no_chart": "0.0",
          "bar": "37.0",
          "line": "0.0"
        }
    }
  }
}

This was the output: 

{
    "pfkb_version": "0.0.0",
    "pfp_version": "0.2.1",
    "staff_number": 6,
    "selected_candidate": {
        "message_template_id": "https://repo.metadatacenter.org/template-instances/55d6b537-7a50-48ae-b97a-01e479bee34d",
        "display": "text only",
        "measure": "NMB03",
        "acceptable_by": [
            "Social better"
        ]
    },
    "selected_comparator": "Peer Top 10%",
    "performance_month": "November 2023",
    "performance_data": "[['staff_number', 'measure', 'month', 'passed_count', 'flagged_count', 'denominator', 'peer_average_comparator', 'peer_75th_percentile_benchmark', 'peer_90th_percentile_benchmark', 'MPOG_goal'], [6, 'NMB03', '2023-01-01', 90, 10, 100, 90, 92, 96, 90], [6, 'NMB03', '2023-02-01', 90, 10, 100, 90, 92, 96, 90], [6, 'NMB03', '2023-03-01', 90, 10, 100, 90, 92, 96, 90], [6, 'NMB03', '2023-04-01', 90, 10, 100, 90, 92, 96, 90], [6, 'NMB03', '2023-05-01', 90, 10, 100, 90, 92, 96, 90], [6, 'NMB03', '2023-06-01', 90, 10, 100, 90, 92, 96, 90], [6, 'NMB03', '2023-07-01', 90, 10, 100, 90, 92, 96, 90], [6, 'NMB03', '2023-08-01', 90, 10, 100, 90, 92, 96, 90], [6, 'NMB03', '2023-09-01', 90, 10, 100, 90, 92, 96, 90], [6, 'NMB03', '2023-10-01', 90, 10, 100, 90, 92, 96, 90], [6, 'NMB03', '2023-11-01', 100, 0, 100, 90, 92, 96, 90], [6, 'NMB03', '2023-12-01', 1, 1, 2, 90, 92, 96, 90]]",
    "message_generated_datetime": "2023-11-17T16:34:22.647997",
    "message": {
        "text_message": "You are a top performer this month for the measure NMB03: NMB Dosing, Pediatrics. Your performance was 100.0% (100/100 cases), above the top 10% peer benchmark, which was 96.0% this month.",
        "measure": "NMB03",
        "measure_full_title": "NMB Dosing, Pediatrics",
        "image": []
    }
}

**Review by zachll — APPROVED** [review]

**Pull request merged**
